# Generated by Django 4.1.3 on 2022-11-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DO_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.IntegerField(default=0)),
                ('do_type', models.CharField(max_length=100)),
                ('permit_number', models.IntegerField(default=0)),
                ('material', models.CharField(max_length=100)),
                ('consigner_name', models.CharField(max_length=100)),
                ('consignee_name', models.CharField(max_length=100)),
                ('do_issue_date', models.DateField()),
                ('do_validity_date', models.DateField()),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('total_do_qty', models.IntegerField(default=0)),
                ('allocate_do_qty', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('do_alias', models.CharField(max_length=100)),
                ('adv_amt_limit', models.IntegerField(default=0)),
                ('diesel_amt_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
