# Generated by Django 4.1.3 on 2022-11-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='do_master',
            name='status',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
