# Generated by Django 4.1.3 on 2022-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_do_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_master',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
